M48
; DRILL file {KiCad 7.0.11} date Tuesday, March 17, 2026 at 11:03:55 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-17T23:03:55-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T2
X100.0Y-97.2
X100.0Y-102.6
T1
X96.77Y-99.91G85X96.77Y-100.51
G05
X103.35Y-100.3G85X103.35Y-99.7
G05
M30
